package Interfaces;

import Fuentes.EmpleadoAsalariado;
import Fuentes.EmpleadoBaseComision;
import Fuentes.EmpleadoComision;
import Fuentes.EmpleadoPorHoras;
import Fuentes.Fecha;
import Fuentes.ListaEmpleado;
import Fuentes.ListaEncadenada;

/**
 *
 * @author danie
 */
public class JFEmpleadosListaEncadenada extends javax.swing.JFrame {

    public ListaEncadenada lista;
    public JFEmpleadosListaEncadenada() {
        initComponents();
        lista = new ListaEncadenada();
        this.setLocationRelativeTo(null);
        this.jTAEmpleadoAsA.setEditable(false);
        this.jTAEmpleadoBaseB.setEditable(false);
        this.jTAEmpleadoComP.setEditable(false);
        this.jTAEmpleadoComiC.setEditable(false);
        this.jTAListaEmpleados.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPEmpleado = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPPorComision = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTFNombresC = new javax.swing.JTextField();
        jTFFEchaNaC = new javax.swing.JTextField();
        jTFFEchaInC = new javax.swing.JTextField();
        jTFVentaTotalC = new javax.swing.JTextField();
        jBAceptarC = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTAEmpleadoComiC = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTFRecibirC = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPPorHoras = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFNombresP = new javax.swing.JTextField();
        jTFFEchaNaP = new javax.swing.JTextField();
        jTFFEchaInP = new javax.swing.JTextField();
        jTFNumnHorasP = new javax.swing.JTextField();
        jBAceptarP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAEmpleadoComP = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTFValorPorHOraP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPBaseMasComision = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTFNombresB = new javax.swing.JTextField();
        jTFFEchaNaB = new javax.swing.JTextField();
        jTFFEchaInB = new javax.swing.JTextField();
        jTFSalarioBaB = new javax.swing.JTextField();
        jBAceptarB = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTAEmpleadoBaseB = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTFTotalVenB = new javax.swing.JTextField();
        jTFPagarB = new javax.swing.JTextField();
        jPAsalariado = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFNombresA = new javax.swing.JTextField();
        jTFFEchaNaA = new javax.swing.JTextField();
        jTFFEchaInA = new javax.swing.JTextField();
        jTFSalarioBaA = new javax.swing.JTextField();
        jBAceptarA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAEmpleadoAsA = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTAListaEmpleados = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jBAlInicio = new javax.swing.JButton();
        jBAlFinal = new javax.swing.JButton();
        jBEnOrden = new javax.swing.JButton();
        jBEliminarNodo = new javax.swing.JButton();
        jTFEmpleadoAEliminar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMISALIR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jLabel20.setText("Nombres");

        jLabel21.setText("Fecha de Nacimiento dd/mm/aaaa");

        jLabel22.setText("Fecha de Ingreso dd/mm/aaaa");

        jLabel23.setText("Venta Total");

        jBAceptarC.setText("ACEPTAR");
        jBAceptarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarCActionPerformed(evt);
            }
        });

        jTAEmpleadoComiC.setColumns(20);
        jTAEmpleadoComiC.setRows(5);
        jScrollPane7.setViewportView(jTAEmpleadoComiC);

        jLabel25.setText("Empleado por Comisión");

        jLabel26.setText("% a recibir");

        javax.swing.GroupLayout jPPorComisionLayout = new javax.swing.GroupLayout(jPPorComision);
        jPPorComision.setLayout(jPPorComisionLayout);
        jPPorComisionLayout.setHorizontalGroup(
            jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPorComisionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPorComisionLayout.createSequentialGroup()
                        .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPPorComisionLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(31, 31, 31)
                                .addComponent(jTFNombresC))
                            .addGroup(jPPorComisionLayout.createSequentialGroup()
                                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFFEchaInC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTFFEchaNaC)
                                    .addComponent(jTFVentaTotalC)
                                    .addComponent(jTFRecibirC))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPorComisionLayout.createSequentialGroup()
                        .addComponent(jBAceptarC)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(24, 24, 24))
        );
        jPPorComisionLayout.setVerticalGroup(
            jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPorComisionLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPPorComisionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTFNombresC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTFFEchaNaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jTFFEchaInC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTFVentaTotalC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPorComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTFRecibirC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAceptarC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPorComisionLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(jPPorComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPPorComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTPEmpleado.addTab("POR COMISIÓN", jPanel3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jLabel7.setText("Nombres");

        jLabel8.setText("Fecha de Nacimiento dd/mm/aaaa");

        jLabel9.setText("Fecha de Ingreso dd/mm/aaaa");

        jLabel10.setText("Número de Horas");

        jBAceptarP.setText("ACEPTAR");
        jBAceptarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarPActionPerformed(evt);
            }
        });

        jTAEmpleadoComP.setColumns(20);
        jTAEmpleadoComP.setRows(5);
        jScrollPane3.setViewportView(jTAEmpleadoComP);

        jLabel12.setText("Empleado por Horas");

        jLabel13.setText("Valor por Hora");

        javax.swing.GroupLayout jPPorHorasLayout = new javax.swing.GroupLayout(jPPorHoras);
        jPPorHoras.setLayout(jPPorHorasLayout);
        jPPorHorasLayout.setHorizontalGroup(
            jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPorHorasLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPorHorasLayout.createSequentialGroup()
                        .addComponent(jBAceptarP)
                        .addGap(207, 224, Short.MAX_VALUE))
                    .addGroup(jPPorHorasLayout.createSequentialGroup()
                        .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPPorHorasLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addComponent(jTFNombresP))
                            .addGroup(jPPorHorasLayout.createSequentialGroup()
                                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFFEchaInP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(jTFFEchaNaP)
                                    .addComponent(jTFNumnHorasP)
                                    .addComponent(jTFValorPorHOraP))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(24, 24, 24))
        );
        jPPorHorasLayout.setVerticalGroup(
            jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPorHorasLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPorHorasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFNombresP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFFEchaNaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTFFEchaInP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTFNumnHorasP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPPorHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTFValorPorHOraP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAceptarP)
                .addGap(19, 19, 19))
            .addGroup(jPPorHorasLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPPorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPPorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTPEmpleado.addTab("POR HORAS", jPanel4);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jLabel14.setText("Nombres");

        jLabel15.setText("Fecha de Nacimiento dd/mm/aaaa");

        jLabel16.setText("Fecha de Ingreso dd/mm/aaaa");

        jLabel17.setText("Salario Base");

        jBAceptarB.setText("ACEPTAR");
        jBAceptarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarBActionPerformed(evt);
            }
        });

        jTAEmpleadoBaseB.setColumns(20);
        jTAEmpleadoBaseB.setRows(5);
        jScrollPane5.setViewportView(jTAEmpleadoBaseB);

        jLabel19.setText("Empleado Base más Comisión");

        jLabel27.setText("Total Vendido");

        jLabel28.setText("%  a Pagar");

        javax.swing.GroupLayout jPBaseMasComisionLayout = new javax.swing.GroupLayout(jPBaseMasComision);
        jPBaseMasComision.setLayout(jPBaseMasComisionLayout);
        jPBaseMasComisionLayout.setHorizontalGroup(
            jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBaseMasComisionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBaseMasComisionLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(31, 31, 31)
                        .addComponent(jTFNombresB))
                    .addGroup(jPBaseMasComisionLayout.createSequentialGroup()
                        .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPBaseMasComisionLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jBAceptarB)))
                        .addGap(6, 6, 6)
                        .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFFEchaInB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jTFFEchaNaB)
                            .addComponent(jTFSalarioBaB)
                            .addComponent(jTFPagarB)
                            .addComponent(jTFTotalVenB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(24, 24, 24))
        );
        jPBaseMasComisionLayout.setVerticalGroup(
            jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBaseMasComisionLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPBaseMasComisionLayout.createSequentialGroup()
                .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBaseMasComisionLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTFNombresB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTFFEchaNaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jTFFEchaInB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTFSalarioBaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFTotalVenB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPBaseMasComisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFPagarB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPBaseMasComisionLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAceptarB))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBaseMasComisionLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBaseMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPBaseMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jTPEmpleado.addTab("BASE MÁS COMISIÓN", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombres");

        jLabel2.setText("Fecha de Nacimiento dd/mm/aaaa");

        jLabel3.setText("Fecha de Ingreso dd/mm/aaaa");

        jLabel4.setText("Salario Básico");

        jBAceptarA.setText("ACEPTAR");
        jBAceptarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarAActionPerformed(evt);
            }
        });

        jTAEmpleadoAsA.setColumns(20);
        jTAEmpleadoAsA.setRows(5);
        jScrollPane1.setViewportView(jTAEmpleadoAsA);

        jLabel6.setText("Empleado Asalariado");

        javax.swing.GroupLayout jPAsalariadoLayout = new javax.swing.GroupLayout(jPAsalariado);
        jPAsalariado.setLayout(jPAsalariadoLayout);
        jPAsalariadoLayout.setHorizontalGroup(
            jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAsalariadoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAsalariadoLayout.createSequentialGroup()
                        .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAsalariadoLayout.createSequentialGroup()
                                .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFFEchaInA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(jTFFEchaNaA)
                                    .addComponent(jTFSalarioBaA)))
                            .addGroup(jPAsalariadoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jTFNombresA)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPAsalariadoLayout.createSequentialGroup()
                        .addComponent(jBAceptarA)
                        .addGap(207, 207, 207)))
                .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24))
        );
        jPAsalariadoLayout.setVerticalGroup(
            jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAsalariadoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPAsalariadoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNombresA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFFEchaNaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTFFEchaInA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAsalariadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFSalarioBaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jBAceptarA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAsalariadoLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTPEmpleado.addTab("ASALARIADO", jPAsalariado);

        jTAListaEmpleados.setColumns(20);
        jTAListaEmpleados.setRows(5);
        jScrollPane9.setViewportView(jTAListaEmpleados);

        jLabel29.setText("Lista de Empleados");

        jBAlInicio.setText("Al Inicio");
        jBAlInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlInicioActionPerformed(evt);
            }
        });

        jBAlFinal.setText("Al Final");
        jBAlFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlFinalActionPerformed(evt);
            }
        });

        jBEnOrden.setText("En Orden");
        jBEnOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnOrdenActionPerformed(evt);
            }
        });

        jBEliminarNodo.setText("Eliminar");
        jBEliminarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarNodoActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMISALIR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        jMISALIR.setText("SALIR");
        jMISALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISALIRActionPerformed(evt);
            }
        });
        jMenu1.add(jMISALIR);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPEmpleado)
                    .addComponent(jScrollPane9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(46, 46, 46)
                        .addComponent(jBAlInicio)
                        .addGap(65, 65, 65)
                        .addComponent(jBAlFinal)
                        .addGap(61, 61, 61)
                        .addComponent(jBEnOrden)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEliminarNodo)
                            .addComponent(jTFEmpleadoAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEliminarNodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBAlInicio)
                        .addComponent(jBAlFinal)
                        .addComponent(jBEnOrden)
                        .addComponent(jTFEmpleadoAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMISALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISALIRActionPerformed

    private void jBAceptarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarAActionPerformed
        
        String nombres = this.jTFNombresA.getText();
        Fecha fechaNacimiento =  new Fecha(this.jTFFEchaNaA.getText());
        Fecha fechaIngreso =  new Fecha(this.jTFFEchaInA.getText());
        double salario = Double.parseDouble(this.jTFSalarioBaA.getText());
        EmpleadoAsalariado empAsa = new EmpleadoAsalariado(salario, fechaIngreso, nombres, fechaNacimiento);
        this.jTAEmpleadoAsA.setText(empAsa.toString());
        lista.addInicio(empAsa);
        this.jTAListaEmpleados.setText(lista.toString());
        
    }//GEN-LAST:event_jBAceptarAActionPerformed

    private void jBAceptarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarPActionPerformed
        
        String nombres = this.jTFNombresP.getText();
        Fecha fechaNacimiento =  new Fecha(this.jTFFEchaNaP.getText());
        Fecha fechaIngreso =  new Fecha(this.jTFFEchaInP.getText());
        int numHoras = Integer.parseInt(this.jTFNumnHorasP.getText());
        double valorHora = Double.parseDouble(this.jTFValorPorHOraP.getText());
        EmpleadoPorHoras empPorHora = new EmpleadoPorHoras(numHoras, valorHora, fechaIngreso, nombres, fechaNacimiento);
        this.jTAEmpleadoComP.setText(empPorHora.toString());
        lista.addInicio(empPorHora);
        this.jTAListaEmpleados.setText(lista.toString());
    }//GEN-LAST:event_jBAceptarPActionPerformed

    private void jBAceptarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarCActionPerformed
      
        String nombres = this.jTFNombresC.getText();
        Fecha fechaNacimiento =  new Fecha(this.jTFFEchaNaC.getText());
        Fecha fechaIngreso =  new Fecha(this.jTFFEchaInC.getText());
        double totalVentas = Double.parseDouble(this.jTFVentaTotalC.getText());
        double valorRecibir = Double.parseDouble(this.jTFRecibirC.getText());
        EmpleadoComision empCon = new EmpleadoComision(totalVentas, valorRecibir, fechaIngreso, nombres, fechaNacimiento);
        this.jTAEmpleadoComiC.setText(empCon.toString());
        lista.addInicio(empCon);        
        this.jTAListaEmpleados.setText(lista.toString());

    }//GEN-LAST:event_jBAceptarCActionPerformed

    private void jBAceptarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarBActionPerformed
       
        String nombres = this.jTFNombresB.getText();
        Fecha fechaNacimiento =  new Fecha(this.jTFFEchaNaB.getText());
        Fecha fechaIngreso =  new Fecha(this.jTFFEchaInB.getText());
        double salarioBase = Double.parseDouble(this.jTFSalarioBaB.getText());
        double totalVentas = Double.parseDouble(this.jTFTotalVenB.getText());
        double valorRecibir = Double.parseDouble(this.jTFPagarB.getText());
        EmpleadoBaseComision empBaseCO = new EmpleadoBaseComision(salarioBase, totalVentas, valorRecibir,  fechaIngreso, nombres, fechaNacimiento);
        this.jTAEmpleadoBaseB.setText(empBaseCO.toString());
        lista.addInicio(empBaseCO);
        this.jTAListaEmpleados.setText(lista.toString());
    }//GEN-LAST:event_jBAceptarBActionPerformed

    private void jBAlInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlInicioActionPerformed
        int i = this.jTPEmpleado.getSelectedIndex();
        
        switch(i){
            case 0:
                String nombres = this.jTFNombresC.getText();
                Fecha fechaNacimiento =  new Fecha(this.jTFFEchaNaC.getText());
                Fecha fechaIngreso =  new Fecha(this.jTFFEchaInC.getText());
                double totalVentas = Double.parseDouble(this.jTFVentaTotalC.getText());
                double valorRecibir = Double.parseDouble(this.jTFRecibirC.getText());
                EmpleadoComision empCon = new EmpleadoComision(totalVentas, valorRecibir, fechaIngreso, nombres, fechaNacimiento);
                this.jTAEmpleadoComiC.setText(empCon.toString());
                lista.addInicio(empCon);        
                this.jTAListaEmpleados.setText(lista.toString());
                
                break;
            
            case 1:
                String nomb = this.jTFNombresP.getText();
                Fecha fechaNacimien =  new Fecha(this.jTFFEchaNaP.getText());
                Fecha fechaIngre =  new Fecha(this.jTFFEchaInP.getText());
                int numHoras = Integer.parseInt(this.jTFNumnHorasP.getText());
                double valorHora = Double.parseDouble(this.jTFValorPorHOraP.getText());
                EmpleadoPorHoras empPorHora = new EmpleadoPorHoras(numHoras, valorHora, fechaIngre, nomb, fechaNacimien);
                this.jTAEmpleadoComP.setText(empPorHora.toString());
                lista.addInicio(empPorHora);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
            case 2:
                String nombress = this.jTFNombresB.getText();
                Fecha fechaNacimientos =  new Fecha(this.jTFFEchaNaB.getText());
                Fecha fechaIngresos =  new Fecha(this.jTFFEchaInB.getText());
                double salarioBase = Double.parseDouble(this.jTFSalarioBaB.getText());
                double totalVentass = Double.parseDouble(this.jTFTotalVenB.getText());
                double valorRecibirs = Double.parseDouble(this.jTFPagarB.getText());
                EmpleadoBaseComision empBaseCO = new EmpleadoBaseComision(salarioBase, totalVentass, valorRecibirs,  fechaIngresos, nombress, fechaNacimientos);
                this.jTAEmpleadoBaseB.setText(empBaseCO.toString());
                lista.addInicio(empBaseCO);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
            case 3:
                String nombre = this.jTFNombresA.getText();
                Fecha fechaNacimient =  new Fecha(this.jTFFEchaNaA.getText());
                Fecha fechaIngres =  new Fecha(this.jTFFEchaInA.getText());
                double salario = Double.parseDouble(this.jTFSalarioBaA.getText());
                EmpleadoAsalariado empAsa = new EmpleadoAsalariado(salario, fechaIngres, nombre, fechaNacimient);
                this.jTAEmpleadoAsA.setText(empAsa.toString());
                lista.addInicio(empAsa);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
        }
    }//GEN-LAST:event_jBAlInicioActionPerformed

    private void jBAlFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlFinalActionPerformed
                                                  
        int i = this.jTPEmpleado.getSelectedIndex();
        
        switch(i){
            case 0:
                String nombres = this.jTFNombresC.getText();
                Fecha fechaNacimiento =  new Fecha(this.jTFFEchaNaC.getText());
                Fecha fechaIngreso =  new Fecha(this.jTFFEchaInC.getText());
                double totalVentas = Double.parseDouble(this.jTFVentaTotalC.getText());
                double valorRecibir = Double.parseDouble(this.jTFRecibirC.getText());
                EmpleadoComision empCon = new EmpleadoComision(totalVentas, valorRecibir, fechaIngreso, nombres, fechaNacimiento);
                this.jTAEmpleadoComiC.setText(empCon.toString());
                lista.addFinal(empCon);        
                this.jTAListaEmpleados.setText(lista.toString());
                
                break;
            
            case 1:
                String nomb = this.jTFNombresP.getText();
                Fecha fechaNacimien =  new Fecha(this.jTFFEchaNaP.getText());
                Fecha fechaIngre =  new Fecha(this.jTFFEchaInP.getText());
                int numHoras = Integer.parseInt(this.jTFNumnHorasP.getText());
                double valorHora = Double.parseDouble(this.jTFValorPorHOraP.getText());
                EmpleadoPorHoras empPorHora = new EmpleadoPorHoras(numHoras, valorHora, fechaIngre, nomb, fechaNacimien);
                this.jTAEmpleadoComP.setText(empPorHora.toString());
                lista.addFinal(empPorHora);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
            case 2:
                String nombress = this.jTFNombresB.getText();
                Fecha fechaNacimientos =  new Fecha(this.jTFFEchaNaB.getText());
                Fecha fechaIngresos =  new Fecha(this.jTFFEchaInB.getText());
                double salarioBase = Double.parseDouble(this.jTFSalarioBaB.getText());
                double totalVentass = Double.parseDouble(this.jTFTotalVenB.getText());
                double valorRecibirs = Double.parseDouble(this.jTFPagarB.getText());
                EmpleadoBaseComision empBaseCO = new EmpleadoBaseComision(salarioBase, totalVentass, valorRecibirs,  fechaIngresos, nombress, fechaNacimientos);
                this.jTAEmpleadoBaseB.setText(empBaseCO.toString());
                lista.addFinal(empBaseCO);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
            case 3:
                String nombre = this.jTFNombresA.getText();
                Fecha fechaNacimient =  new Fecha(this.jTFFEchaNaA.getText());
                Fecha fechaIngres =  new Fecha(this.jTFFEchaInA.getText());
                double salario = Double.parseDouble(this.jTFSalarioBaA.getText());
                EmpleadoAsalariado empAsa = new EmpleadoAsalariado(salario, fechaIngres, nombre, fechaNacimient);
                this.jTAEmpleadoAsA.setText(empAsa.toString());
                lista.addFinal(empAsa);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
        }
    }//GEN-LAST:event_jBAlFinalActionPerformed

    private void jBEnOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnOrdenActionPerformed
        int i = this.jTPEmpleado.getSelectedIndex();
        
        switch(i){
            case 0:
                String nombres = this.jTFNombresC.getText();
                Fecha fechaNacimiento =  new Fecha(this.jTFFEchaNaC.getText());
                Fecha fechaIngreso =  new Fecha(this.jTFFEchaInC.getText());
                double totalVentas = Double.parseDouble(this.jTFVentaTotalC.getText());
                double valorRecibir = Double.parseDouble(this.jTFRecibirC.getText());
                EmpleadoComision empCon = new EmpleadoComision(totalVentas, valorRecibir, fechaIngreso, nombres, fechaNacimiento);
                this.jTAEmpleadoComiC.setText(empCon.toString());
                lista.addOrden(empCon);        
                this.jTAListaEmpleados.setText(lista.toString());
                
                break;
            
            case 1:
                String nomb = this.jTFNombresP.getText();
                Fecha fechaNacimien =  new Fecha(this.jTFFEchaNaP.getText());
                Fecha fechaIngre =  new Fecha(this.jTFFEchaInP.getText());
                int numHoras = Integer.parseInt(this.jTFNumnHorasP.getText());
                double valorHora = Double.parseDouble(this.jTFValorPorHOraP.getText());
                EmpleadoPorHoras empPorHora = new EmpleadoPorHoras(numHoras, valorHora, fechaIngre, nomb, fechaNacimien);
                this.jTAEmpleadoComP.setText(empPorHora.toString());
                lista.addOrden(empPorHora);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
            case 2:
                String nombress = this.jTFNombresB.getText();
                Fecha fechaNacimientos =  new Fecha(this.jTFFEchaNaB.getText());
                Fecha fechaIngresos =  new Fecha(this.jTFFEchaInB.getText());
                double salarioBase = Double.parseDouble(this.jTFSalarioBaB.getText());
                double totalVentass = Double.parseDouble(this.jTFTotalVenB.getText());
                double valorRecibirs = Double.parseDouble(this.jTFPagarB.getText());
                EmpleadoBaseComision empBaseCO = new EmpleadoBaseComision(salarioBase, totalVentass, valorRecibirs,  fechaIngresos, nombress, fechaNacimientos);
                this.jTAEmpleadoBaseB.setText(empBaseCO.toString());
                lista.addOrden(empBaseCO);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
            case 3:
                String nombre = this.jTFNombresA.getText();
                Fecha fechaNacimient =  new Fecha(this.jTFFEchaNaA.getText());
                Fecha fechaIngres =  new Fecha(this.jTFFEchaInA.getText());
                double salario = Double.parseDouble(this.jTFSalarioBaA.getText());
                EmpleadoAsalariado empAsa = new EmpleadoAsalariado(salario, fechaIngres, nombre, fechaNacimient);
                this.jTAEmpleadoAsA.setText(empAsa.toString());
                lista.addOrden(empAsa);
                this.jTAListaEmpleados.setText(lista.toString());
                break;
        }
    }//GEN-LAST:event_jBEnOrdenActionPerformed

    private void jBEliminarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarNodoActionPerformed
        String nombreEliminar = this.jTFEmpleadoAEliminar.getText();
        lista.eliminarNodo(nombreEliminar);
        this.jTAListaEmpleados.setText(lista.toString());
        this.jTFEmpleadoAEliminar.setText("");
        this.jTFEmpleadoAEliminar.requestFocus();
    }//GEN-LAST:event_jBEliminarNodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmpleadosListaEncadenada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmpleadosListaEncadenada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmpleadosListaEncadenada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmpleadosListaEncadenada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmpleadosListaEncadenada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarA;
    private javax.swing.JButton jBAceptarB;
    private javax.swing.JButton jBAceptarC;
    private javax.swing.JButton jBAceptarP;
    private javax.swing.JButton jBAlFinal;
    private javax.swing.JButton jBAlInicio;
    private javax.swing.JButton jBEliminarNodo;
    private javax.swing.JButton jBEnOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMISALIR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPAsalariado;
    private javax.swing.JPanel jPBaseMasComision;
    private javax.swing.JPanel jPPorComision;
    private javax.swing.JPanel jPPorHoras;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTAEmpleadoAsA;
    private javax.swing.JTextArea jTAEmpleadoBaseB;
    private javax.swing.JTextArea jTAEmpleadoComP;
    private javax.swing.JTextArea jTAEmpleadoComiC;
    private javax.swing.JTextArea jTAListaEmpleados;
    private javax.swing.JTextField jTFEmpleadoAEliminar;
    private javax.swing.JTextField jTFFEchaInA;
    private javax.swing.JTextField jTFFEchaInB;
    private javax.swing.JTextField jTFFEchaInC;
    private javax.swing.JTextField jTFFEchaInP;
    private javax.swing.JTextField jTFFEchaNaA;
    private javax.swing.JTextField jTFFEchaNaB;
    private javax.swing.JTextField jTFFEchaNaC;
    private javax.swing.JTextField jTFFEchaNaP;
    private javax.swing.JTextField jTFNombresA;
    private javax.swing.JTextField jTFNombresB;
    private javax.swing.JTextField jTFNombresC;
    private javax.swing.JTextField jTFNombresP;
    private javax.swing.JTextField jTFNumnHorasP;
    private javax.swing.JTextField jTFPagarB;
    private javax.swing.JTextField jTFRecibirC;
    private javax.swing.JTextField jTFSalarioBaA;
    private javax.swing.JTextField jTFSalarioBaB;
    private javax.swing.JTextField jTFTotalVenB;
    private javax.swing.JTextField jTFValorPorHOraP;
    private javax.swing.JTextField jTFVentaTotalC;
    private javax.swing.JTabbedPane jTPEmpleado;
    // End of variables declaration//GEN-END:variables
}
